#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 15 12:03:07 2018

@author: pratik
"""

import pandas as pd;
series = pd.Series(['Element1','Element2'])
data_frame = pd.DataFrame({'element1': series})


california_housing_dataframe = pd.read_csv("https://storage.googleapis.com/mledu-datasets/california_housing_train.csv", sep=",")
longitude = california_housing_dataframe['longitude']
longitude = longitude/0.1
california_housing_dataframe.describe()
california_housing_dataframe['rich'] = pd.Series(len(california_housing_dataframe['longitude']))
california_housing_dataframe['rich'] = california_housing_dataframe.rich.astype(str)
california_housing_dataframe.at[0,'rich'] = 'True'

import math

def distance(origin, destination):
    lat1, lon1 = origin
    lat2, lon2 = destination
    radius = 6371 # km

    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius * c

    return d
    
california_housing_dataframe['rich'].apply(lambda val: ('Yes' if val=='False' else 'No'))
for index,row in california_housing_dataframe.iterrows():
   if(print(row['median_income']>2.0)):
       california_housing_dataframe.at[index,'rich'] = 'True'
   else:
      california_housing_dataframe.at[index,'rich'] = 'False'
